### PR TITLE
Cache source identifiers fix

### PR DESCRIPTION
**Pull request by damarte**
Use MD5 instead of hash for cache source identifier generation.

Remove NSHomeDirectory from cache source identifier generation.

### CODE REVIEW

**Review by alexgarbarev — APPROVED** [review]

**Comment by alexgarbarev** [comment]
Hey @damarte! Thanks for the input. This looks useful to me. 
Could you please add NSString+Hash category to the project file, to pass tests.

**Comment by damarte** [comment]
Done

**Comment by alexgarbarev** [comment]
Great! I'll push a new release quickly

**Comment by alexgarbarev** [comment]
Pushed as `1.0.8` to Cocoapods.

**Pull request merged**
